spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  jmx:
    default-domain: ex-emp-management
  # Spring Security .defaultSuccessUrl("/employee/showList", false)とした場合に初回のログインが失敗する現象に対応
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration